apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb
data:
  init-db.sh: |
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
        CREATE DATABASE foodway;
    EOSQL